### ISSUE TITLE
小Bug

### ISSUE THREAD

**Issue by raging-flames** [Kelfvin/JianTi#1]
![Screenshot_20221016_091815](https://user-images.githubusercontent.com/67429400/196013412-1c51c20b-8e49-44f5-84c5-271b4be73dfa.jpg)

**Comment by Kelfvin** [comment]
好的，已收到。

**Comment by Kelfvin** [comment]
可以描述一下是怎么触发的吗？

**Comment by raging-flames** [comment]
> 

尝试了几次都没有复现，所以问题应该不大。当时是点了选项没有反应，再点就这样了😂

**Comment by Kelfvin** [comment]
哦哦，我这边先记录一下，有时间再看看。最近挺忙的
