### ISSUE TITLE
一些小建议

### ISSUE THREAD

**Issue by raging-flames** [Kelfvin/JianTi#2]
1.长按题目可以复制。方便搜索答案解析。
2.做题页面可以左右滑动切换上下题目。
3.多选题点勾勾确认答案后，如果错误也不再显示勾勾键，如图，有可能挡住题目而且也没必要。
![Screenshot_20221103_092259](https://user-images.githubusercontent.com/67429400/199632199-faa4a7d4-149f-44ab-b244-b201674a974d.jpg)
加上滑动切题，然后把「下一题」改成勾勾键可能是一种方法。
当然以上是建议，简题总体来说还是不错的，如果你有时间或者觉得有必要可以参考参考。（＾ｖ＾）

**Comment by Kelfvin** [comment]
1. 题目复制这个不错哈，我考虑一下。
2. 滑动切换，这个已经加入计划了
3. 对于多选的勾勾，下个版本改进

谢谢你的建议，最近挺忙的，好多课程要学。等有空了就改进。
