### ISSUE TITLE
又些小建议

### ISSUE THREAD

**Issue by raging-flames** [Kelfvin/JianTi#3]
又用了一段时间，发现了一些不方便之处
1.「开始练题」相关:记忆上次做题位置挺好的，不过当一章题做完后再点开做，仍会是完成页面，此时如果想再做一遍，只能狂狂狂点上一题😂。建议这种情况下再点开是会自动回到第一题，或者完成页面添加一个回到第一题的按键。
2.「错题」相关:
（感觉规则有些不清晰，似乎做对了就不会出现，但数量好像没减少，或者是连续做对几次才自动移出错题?不清楚。)
主要影响是，一学科一个错题，当题做多了以后，错题就会很多，比如我做完了第二章，错了几十题，我只想练习这几十题，但是错题里包含本学科之前错过的题...
因此这方面建议每一章单独一个错题，一道题连续做对两次或者三次自动移出(虽然添加手动移除，自定义连续对次数可能更好，但是应该会麻烦很多，比较你也忙)
3.「新功能建议」:建议加个收藏夹，有些题不熟，可能某次猜对了，我想以后多做几次，现在的话，只能后退然后点错的。
如果觉得有必要又有时间可以参考参考

**Comment by Kelfvin** [comment]
记录一下，但是真的忙不过来了，没得时间弄这个
